### PR TITLE
Hex trim

### PR DESCRIPTION
**Pull request by blemasle**
Hi (again),

Note : this pull request *will* conflict with the [other one](https://github.com/MajicDesigns/MD_DS3231/pull/8) I just opened because of some whitespaces. I kept both changesets separated so you can easily discard this one if you don't like it, while retaining the bugfixes. I'll deal with the conflicts on my fork, but I opened this
PR without waiting for the other because I anticipate that wyou'll want to discuss this one :)

This pull request allow to shrink down the library size in a substantial way.
 * Around 300 bytes with all features
 * 370 additional bytes by disabling 12H clock mode
 * 84 additional bytes by disabling day of week support

Some additional changes :
 * Removed `ENABLE_TEMP_COMP` : GCC will take care of that for you. The 'flag' is wether you use the function or not
 * Added `ENABLE_CUSTOM_CENTURY` : Just here for backward compatibility, but you might as well remove *dynamic* century support from the library and rely on the define.

All the changes are backward compatibles.

As a sidenote, 150 bytes of HEX space and 7 bytes of RAM can be saved by moving the interface registers
to function parameters (using a `struct` for conviniency). That would be a breaking changes but would also
made things cleaner as there would no longer be some outdated/irrelevant data in those registers.

Here are the numbers of an empty sketch with all of `MD_DS3231` code forced included, and conditionnal features removed.

Features        | Space (bytes)         | Ram (bytes)
----------------|-----------------------|------------------
v1.2.4          | 6344                  | 265
All features    | 6066                  | 240
ENABLE_12H 0    | 5696                  | 239
ENABLE_DOW 0    | 5982                  | 239

Hope you'll like it !
Regards

### CODE REVIEW

**Comment by MajicDesigns** [comment]
Quite an extensive set of changes.
What testing have you done for this? I don't really have the time to test much as I am busy with other stuff at the moment.
Any breaking changes in this (looks like not, but please confirm).
Would also be useful for you to remove the conflicts before this is merged.

**Comment by blemasle** [comment]
Yes I know that a lot of change.
I did pay attention to not introduce any breaking changes.

Regarding the test, I played around with the tester program with write & read time and alarms (both of them).

I'm also currently using this version of the library in a device that relies solely on accurate time and alarm1 interrupts to work.

I can do any additional testing that you would judge necessary of course.

And finally, as said in the PR, now that you have merged the other PR, I can solve the conflicts for this one :)

Cheers

**Comment by blemasle** [comment]
I updated the branch with the bugfixes PR.
If you have any doubt about this, feel free to discard this PR of course. I doubt this is an important issue for most of your users :)

**Comment by MajicDesigns** [comment]
Issued as version 1.3.0

**Pull request merged**
